services:
  postgres:
    image: postgres:latest
    container_name: shop_postgres
    environment:
      POSTGRES_DB: db_shop
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - friterieshop-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    container_name: shop_api
    build:
      context: .
      dockerfile: ./FriterieShop.Presentation/FriterieShop.API/Dockers/Dockerfile
    depends_on:
      - postgres
    networks:
      - friterieshop-network
    environment:
      ConnectionStrings__DefaultConnection: "Host=postgres;Database=db_shop;Username=postgres;Password=postgres"
      Frontend__BaseUrl: "http://localhost:5209"
      ASPNETCORE_URLS: "http://+:8080"
    ports:
      - "5282:8080"

  web:
    container_name: shop_web
    build:
      context: .
      dockerfile: ./FriterieShop.Presentation/FriterieShop.Web/Dockers/Dockerfile
    depends_on:
      - api
    networks:
      - friterieshop-network
    environment:
      API_BASE_URL: "http://api:8080/api/"
    ports:
      - "5209:80"

volumes:
  postgres-data:
    driver: local

networks:
  friterieshop-network:
    driver: bridge